#pragma once

#define IHTATRACKING_VERSION "1.0.0"

#define IHTATRACKING_VERSION_MAJOR 1
#define IHTATRACKING_VERSION_MINOR 0
#define IHTATRACKING_VERSION_PATCH 0
#define IHTATRACKING_VERSION_TWEAK 0
