#pragma once

#define IHTAPROFILER_VERSION "1.0.0"

#define IHTAPROFILER_VERSION_MAJOR 1
#define IHTAPROFILER_VERSION_MINOR 0
#define IHTAPROFILER_VERSION_PATCH 0
#define IHTAPROFILER_VERSION_TWEAK 0
